name: Release

on:
  workflow_dispatch:
    inputs:
      bumpType:
        type: choice
        description: "Bump type: major | minor | patch"
        required: true
        default: "patch"
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: ${{ github.event.inputs.bumpType || 'patch' }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Voyage docker image
        run: sh build.sh

      - name: Push Voyage docker image
        run: |
          TAG=$(cat version.txt)
          docker push mschnr/voyage:${TAG}
          docker push mschnr/voyage:latest
